from __future__ import annotations

from typing import Any, Protocol

from .domain import ActionProposal, Evidence, IncidentRequest, TaskRecord


class Planner(Protocol):
    async def plan(self, request: IncidentRequest) -> list[str]: ...


class Investigator(Protocol):
    async def collect(self, request: IncidentRequest, plan: list[str]) -> list[Evidence | dict[str, Any]]: ...


class Executor(Protocol):
    async def execute(self, proposal: ActionProposal) -> dict[str, Any]: ...


class TaskStore(Protocol):
    async def get_by_request_id(self, request_id: str) -> TaskRecord | None: ...
    async def get(self, task_id: str) -> TaskRecord | None: ...
    async def create(self, task: TaskRecord) -> TaskRecord: ...
    async def save(self, task: TaskRecord) -> TaskRecord: ...
    async def claim_execution(self, task_id: str) -> bool: ...
